if(NOT DEFINED CMAKE_MSVC_RUNTIME_LIBRARY)
    message(FATAL_ERROR "CMAKE_MSVC_RUNTIME_LIBRARY is not defined")
endif()

if(NOT CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL "MultiThreadedDebug"
   AND NOT CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL "MultiThreaded"
   AND NOT CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL "MultiThreaded$<$<CONFIG:Debug>:Debug>")
    message(FATAL_ERROR "Unexpected CMAKE_MSVC_RUNTIME_LIBRARY='${CMAKE_MSVC_RUNTIME_LIBRARY}'")
endif()
